services:

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - app

  app:
    image: ghcr.io/gibanator/dailystep-backend:latest
    container_name: dailystep

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "8080"

    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data:

  caddy_data:

  caddy_config:
